TRAIN_DEV_TEST_DIR=data/en-de/train_dev_test

diff_length : $(TRAIN_DEV_TEST_DIR)/diff_length_src_labels.ids
$(TRAIN_DEV_TEST_DIR)/diff_length_src_labels.ids : $(SPLIT_TOKEN_DIR)/all.src.limit.txt.gz $(ANNOT_DIR)/all.labels.limit.txt.gz
	paste <(zcat $(word 1,$^)) <(zcat $(word 2,$^)) |\
	perl -ne 'chomp $$_; @c = split /\t/, $$_; @co = map {scalar split / /, $$_} @c; if ($$co[0] != $$co[1]) { print "$$_\n"; } else { print "OK\n"; }' |\
	cat -n | grep -v "OK" | cut -f1 | sed 's/$$/d/' > $@

$(TRAIN_DEV_TEST_DIR)/all.src.limit.txt.gz : $(SPLIT_TOKEN_DIR)/all.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/diff_length_src_labels.ids
	zcat $(word 1,$^) | sed -f $(word 2,$^) | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/all.labels.limit.txt.gz : $(ANNOT_DIR)/all.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/diff_length_src_labels.ids
	zcat $(word 1,$^) | sed -f $(word 2,$^) | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz : $(BITEXT_LEMMA_DIR)/all.ids.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/diff_length_src_labels.ids
	zcat $(word 1,$^) | sed -f $(word 2,$^) | gzip -c > $@

wmt16-ape-train : REGEX=wmt16-ape/train/
wmt17-ape-train : REGEX=wmt17-ape/train/
wmt18-ape-train : REGEX=wmt18-ape/train/
wmt16-ape-train : $(TRAIN_DEV_TEST_DIR)/wmt16-ape-train.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/wmt16-ape-train.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/wmt16-ape-train.ids.limit.txt.gz
wmt17-ape-train : $(TRAIN_DEV_TEST_DIR)/wmt17-ape-train.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/wmt17-ape-train.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/wmt17-ape-train.ids.limit.txt.gz
wmt18-ape-train : $(TRAIN_DEV_TEST_DIR)/wmt18-ape-train.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/wmt18-ape-train.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/wmt18-ape-train.ids.limit.txt.gz
$(TRAIN_DEV_TEST_DIR)/wmt16-ape-train.src.limit.txt.gz \
$(TRAIN_DEV_TEST_DIR)/wmt17-ape-train.src.limit.txt.gz \
$(TRAIN_DEV_TEST_DIR)/wmt18-ape-train.src.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX)' | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/wmt16-ape-train.labels.limit.txt.gz \
$(TRAIN_DEV_TEST_DIR)/wmt17-ape-train.labels.limit.txt.gz \
$(TRAIN_DEV_TEST_DIR)/wmt18-ape-train.labels.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX)' | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/wmt16-ape-train.ids.limit.txt.gz \
$(TRAIN_DEV_TEST_DIR)/wmt17-ape-train.ids.limit.txt.gz \
$(TRAIN_DEV_TEST_DIR)/wmt18-ape-train.ids.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	zcat $< | grep -P '^\S*$(REGEX)' | gzip -c > $@

DEV_SIZE=971727
TEST_SIZE=971728

train-amunmt16-escape18-ape : REGEX=(amunmt16|escape18)-ape/
train-amunmt16-escape18-ape : $(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape.ids.limit.txt.gz
$(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape.src.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX)' | shuffle --random_seed 1986 |\
	tail -n+$$(($(TEST_SIZE)+$(DEV_SIZE)+1)) | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape.labels.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX)' | shuffle --random_seed 1986 |\
	tail -n+$$(($(TEST_SIZE)+$(DEV_SIZE)+1)) | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape.ids.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	zcat $< | grep -P '^\S*$(REGEX)' | shuffle --random_seed 1986 |\
	tail -n+$$(($(TEST_SIZE)+$(DEV_SIZE)+1)) | gzip -c > $@

train-amunmt16-escape18-ape-nmt : REGEX1=(amunmt16|escape18)-ape/
train-amunmt16-escape18-ape-nmt : REGEX2=(amunmt16|escape18)-ape/(4M|500K|NMT)/
train-amunmt16-escape18-ape-nmt : $(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape-nmt.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape-nmt.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape-nmt.ids.limit.txt.gz
$(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape-nmt.src.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	tail -n+$$(($(TEST_SIZE)+$(DEV_SIZE)+1)) | \
	grep -P "^\S*$(REGEX2)" | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape-nmt.labels.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	tail -n+$$(($(TEST_SIZE)+$(DEV_SIZE)+1)) | \
	grep -P "^\S*$(REGEX2)" | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/train-amunmt16-escape18-ape-nmt.ids.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	zcat $< | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	tail -n+$$(($(TEST_SIZE)+$(DEV_SIZE)+1)) | \
	grep -P "^\S*$(REGEX2)" | gzip -c > $@

dev-amunmt16-ape-4m dev-amunmt16-ape-500k dev-escape18-ape-nmt dev-escape18-ape-pbsmt: REGEX1=(amunmt16|escape18)-ape/
dev-amunmt16-ape-4m : REGEX2=amunmt16-ape/4M/
dev-amunmt16-ape-500k : REGEX2=amunmt16-ape/500K/
dev-escape18-ape-nmt : REGEX2=escape18-ape/NMT/
dev-escape18-ape-pbsmt : REGEX2=escape18-ape/PBSMT/
dev-amunmt16-ape-4m : $(TRAIN_DEV_TEST_DIR)/dev-amunmt16-ape-4m.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/dev-amunmt16-ape-4m.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/dev-amunmt16-ape-4m.ids.limit.txt.gz
dev-amunmt16-ape-500k : $(TRAIN_DEV_TEST_DIR)/dev-amunmt16-ape-500k.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/dev-amunmt16-ape-500k.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/dev-amunmt16-ape-500k.ids.limit.txt.gz
dev-escape18-ape-nmt : $(TRAIN_DEV_TEST_DIR)/dev-escape18-ape-nmt.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/dev-escape18-ape-nmt.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/dev-escape18-ape-nmt.ids.limit.txt.gz
dev-escape18-ape-pbsmt : $(TRAIN_DEV_TEST_DIR)/dev-escape18-ape-pbsmt.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/dev-escape18-ape-pbsmt.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/dev-escape18-ape-pbsmt.ids.limit.txt.gz
$(TRAIN_DEV_TEST_DIR)/dev-%.src.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	head -n+$$(($(TEST_SIZE)+$(DEV_SIZE))) | tail -n $(DEV_SIZE) | grep -P '^\S*$(REGEX2)' | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/dev-%.labels.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	head -n+$$(($(TEST_SIZE)+$(DEV_SIZE))) | tail -n $(DEV_SIZE) | grep -P '^\S*$(REGEX2)' | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/dev-%.ids.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	zcat $< | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	head -n+$$(($(TEST_SIZE)+$(DEV_SIZE))) | tail -n $(DEV_SIZE) | grep -P '^\S*$(REGEX2)' | gzip -c > $@

test-amunmt16-ape-4m test-amunmt16-ape-500k test-escape18-ape-nmt test-escape18-ape-pbsmt: REGEX1=(amunmt16|escape18)-ape/
test-amunmt16-ape-4m : REGEX2=amunmt16-ape/4M/
test-amunmt16-ape-500k : REGEX2=amunmt16-ape/500K/
test-escape18-ape-nmt : REGEX2=escape18-ape/NMT/
test-escape18-ape-pbsmt : REGEX2=escape18-ape/PBSMT/
test-amunmt16-ape-4m : $(TRAIN_DEV_TEST_DIR)/test-amunmt16-ape-4m.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/test-amunmt16-ape-4m.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/test-amunmt16-ape-4m.ids.limit.txt.gz
test-amunmt16-ape-500k : $(TRAIN_DEV_TEST_DIR)/test-amunmt16-ape-500k.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/test-amunmt16-ape-500k.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/test-amunmt16-ape-500k.ids.limit.txt.gz
test-escape18-ape-nmt : $(TRAIN_DEV_TEST_DIR)/test-escape18-ape-nmt.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/test-escape18-ape-nmt.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/test-escape18-ape-nmt.ids.limit.txt.gz
test-escape18-ape-pbsmt : $(TRAIN_DEV_TEST_DIR)/test-escape18-ape-pbsmt.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/test-escape18-ape-pbsmt.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/test-escape18-ape-pbsmt.ids.limit.txt.gz
$(TRAIN_DEV_TEST_DIR)/test-%.src.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.src.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	head -n+$$(($(TEST_SIZE)+$(DEV_SIZE))) | head -n $(TEST_SIZE) | grep -P '^\S*$(REGEX2)' | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/test-%.labels.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.labels.limit.txt.gz $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	paste <(zcat $(word 2,$^)) <(zcat $(word 1,$^)) | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	head -n+$$(($(TEST_SIZE)+$(DEV_SIZE))) | head -n $(TEST_SIZE) | grep -P '^\S*$(REGEX2)' | cut -f2 | gzip -c > $@
$(TRAIN_DEV_TEST_DIR)/test-%.ids.limit.txt.gz: $(TRAIN_DEV_TEST_DIR)/all.ids.limit.txt.gz
	zcat $< | grep -P '^\S*$(REGEX1)' | shuffle --random_seed 1986 |\
	head -n+$$(($(TEST_SIZE)+$(DEV_SIZE))) | head -n $(TEST_SIZE) | grep -P '^\S*$(REGEX2)' | gzip -c > $@
